# Generated by Django 3.1 on 2020-08-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
